# Generated by Django 3.2.15 on 2022-10-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_schedule', '0001_initial'),
        ('app_seat', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_schedule.schedule')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seat.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.user')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Бронирование',
                'db_table': 'bookings',
            },
        ),
    ]
