# Generated by Django 3.2.15 on 2022-10-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_hall', '0001_initial'),
        ('app_film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_price', models.IntegerField()),
                ('rental_duration', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_film.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hall.hall')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'db_table': 'schedules',
            },
        ),
    ]
