# Generated by Django 4.1.1 on 2022-10-17 19:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating', models.CharField(choices=[('vip seating', 'vip seating'), ('classical seating', 'classical seating'), ('kid seating', 'kid seating')], default='classical seating', max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hall.hall')),
            ],
            options={
                'db_table': 'seats',
            },
        ),
    ]
