# Generated by Django 3.2.15 on 2022-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('STD', 'Standard')], default='STD', max_length=3)),
                ('is_free', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Сиденье',
                'verbose_name_plural': 'Сиденья',
                'db_table': 'seats',
            },
        ),
    ]
