# Generated by Django 3.2.16 on 2022-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('max_people_count', models.IntegerField()),
            ],
            options={
                'db_table': 'halls',
            },
        ),
    ]
