# Generated by Django 3.2.15 on 2022-10-05 14:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('duration', models.IntegerField()),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'films',
            },
        ),
    ]
