# Generated by Django 4.1.1 on 2022-10-18 12:00

import app_film.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=django_enumfield.db.fields.EnumField(default=1, enum=app_film.models.Genres),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=django_enumfield.db.fields.EnumField(default=1, enum=app_film.models.Languages),
        ),
    ]
