# Generated by Django 4.1.1 on 2022-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.DateField(),
        ),
    ]
